package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.RedisContent;

public interface RedisContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    int insert(RedisContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    int insertSelective(RedisContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    RedisContent selectByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RedisContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redis_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RedisContent record);
}