package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.SocketContent;

public interface SocketContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    int insert(SocketContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    int insertSelective(SocketContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    SocketContent selectByPrimaryKey(String contentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SocketContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SocketContent record);
}