package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.SysConUserRole;

public interface SysConUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String conUrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    int insert(SysConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    int insertSelective(SysConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    SysConUserRole selectByPrimaryKey(String conUrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysConUserRole record);
}