package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.UserUser;

public interface UserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insert(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int insertSelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    UserUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserUser record);
}