package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.UserConRolePermission;

public interface UserConRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String conRpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    int insert(UserConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(UserConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    UserConRolePermission selectByPrimaryKey(String conRpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserConRolePermission record);
}