package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.UserConUserRole;

public interface UserConUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String conUrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    int insert(UserConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    int insertSelective(UserConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    UserConUserRole selectByPrimaryKey(String conUrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserConUserRole record);
}