package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.WebConRolePermission;

public interface WebConRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String conrpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    int insert(WebConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(WebConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    WebConRolePermission selectByPrimaryKey(String conrpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebConRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebConRolePermission record);
}