package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.WebConUserRole;

public interface WebConUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String conurid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    int insert(WebConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    int insertSelective(WebConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    WebConUserRole selectByPrimaryKey(String conurid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebConUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_con_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebConUserRole record);
}