package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.WebPermission;

public interface WebPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String perid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    int insert(WebPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    int insertSelective(WebPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    WebPermission selectByPrimaryKey(String perid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebPermission record);
}