package com.chengjs.cjsssmsweb.dao.master;

import com.chengjs.cjsssmsweb.pojo.WebUser;

public interface WebUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    int insert(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    int insertSelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    WebUser selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebUser record);
}