package com.chengjs.cjsssmsweb.daomybatis.master;

import com.chengjs.cjsssmsweb.pojo.SysConRolePermission;

public interface SysConRolePermissionMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  int deleteByPrimaryKey(String conRpId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  int insert(SysConRolePermission record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  int insertSelective(SysConRolePermission record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  SysConRolePermission selectByPrimaryKey(String conRpId);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(SysConRolePermission record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_con_role_permission
   *
   * @mbggenerated
   */
  int updateByPrimaryKey(SysConRolePermission record);
}