package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class SocketContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socket_content.contentid
     *
     * @mbggenerated
     */
    private String contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socket_content.contentSender
     *
     * @mbggenerated
     */
    private String contentsender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socket_content.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column socket_content.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socket_content.contentid
     *
     * @return the value of socket_content.contentid
     *
     * @mbggenerated
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socket_content.contentid
     *
     * @param contentid the value for socket_content.contentid
     *
     * @mbggenerated
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socket_content.contentSender
     *
     * @return the value of socket_content.contentSender
     *
     * @mbggenerated
     */
    public String getContentsender() {
        return contentsender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socket_content.contentSender
     *
     * @param contentsender the value for socket_content.contentSender
     *
     * @mbggenerated
     */
    public void setContentsender(String contentsender) {
        this.contentsender = contentsender == null ? null : contentsender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socket_content.content
     *
     * @return the value of socket_content.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socket_content.content
     *
     * @param content the value for socket_content.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column socket_content.createtime
     *
     * @return the value of socket_content.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column socket_content.createtime
     *
     * @param createtime the value for socket_content.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}