package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class SysConUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.conurid
     *
     * @mbggenerated
     */
    private String conurid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.roleid
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.discard
     *
     * @mbggenerated
     */
    private String discard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.conurid
     *
     * @return the value of sys_con_user_role.conurid
     *
     * @mbggenerated
     */
    public String getConurid() {
        return conurid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.conurid
     *
     * @param conurid the value for sys_con_user_role.conurid
     *
     * @mbggenerated
     */
    public void setConurid(String conurid) {
        this.conurid = conurid == null ? null : conurid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.userid
     *
     * @return the value of sys_con_user_role.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.userid
     *
     * @param userid the value for sys_con_user_role.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.roleid
     *
     * @return the value of sys_con_user_role.roleid
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.roleid
     *
     * @param roleid the value for sys_con_user_role.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.createtime
     *
     * @return the value of sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.createtime
     *
     * @param createtime the value for sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.modifytime
     *
     * @return the value of sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.modifytime
     *
     * @param modifytime the value for sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.discard
     *
     * @return the value of sys_con_user_role.discard
     *
     * @mbggenerated
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.discard
     *
     * @param discard the value for sys_con_user_role.discard
     *
     * @mbggenerated
     */
    public void setDiscard(String discard) {
        this.discard = discard == null ? null : discard.trim();
    }
}