package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class SysConRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.conrpid
     *
     * @mbggenerated
     */
    private String conrpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.roleid
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.perid
     *
     * @mbggenerated
     */
    private String perid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_role_permission.discard
     *
     * @mbggenerated
     */
    private String discard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.conrpid
     *
     * @return the value of sys_con_role_permission.conrpid
     *
     * @mbggenerated
     */
    public String getConrpid() {
        return conrpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.conrpid
     *
     * @param conrpid the value for sys_con_role_permission.conrpid
     *
     * @mbggenerated
     */
    public void setConrpid(String conrpid) {
        this.conrpid = conrpid == null ? null : conrpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.roleid
     *
     * @return the value of sys_con_role_permission.roleid
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.roleid
     *
     * @param roleid the value for sys_con_role_permission.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.perid
     *
     * @return the value of sys_con_role_permission.perid
     *
     * @mbggenerated
     */
    public String getPerid() {
        return perid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.perid
     *
     * @param perid the value for sys_con_role_permission.perid
     *
     * @mbggenerated
     */
    public void setPerid(String perid) {
        this.perid = perid == null ? null : perid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.createtime
     *
     * @return the value of sys_con_role_permission.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.createtime
     *
     * @param createtime the value for sys_con_role_permission.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.modifytime
     *
     * @return the value of sys_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.modifytime
     *
     * @param modifytime the value for sys_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_role_permission.discard
     *
     * @return the value of sys_con_role_permission.discard
     *
     * @mbggenerated
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_role_permission.discard
     *
     * @param discard the value for sys_con_role_permission.discard
     *
     * @mbggenerated
     */
    public void setDiscard(String discard) {
        this.discard = discard == null ? null : discard.trim();
    }
}