package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class SysConUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.con_ur_id
     *
     * @mbggenerated
     */
    private String conUrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_con_user_role.discard
     *
     * @mbggenerated
     */
    private String discard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.con_ur_id
     *
     * @return the value of sys_con_user_role.con_ur_id
     *
     * @mbggenerated
     */
    public String getConUrId() {
        return conUrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.con_ur_id
     *
     * @param conUrId the value for sys_con_user_role.con_ur_id
     *
     * @mbggenerated
     */
    public void setConUrId(String conUrId) {
        this.conUrId = conUrId == null ? null : conUrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.user_id
     *
     * @return the value of sys_con_user_role.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.user_id
     *
     * @param userId the value for sys_con_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.role_id
     *
     * @return the value of sys_con_user_role.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.role_id
     *
     * @param roleId the value for sys_con_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.createtime
     *
     * @return the value of sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.createtime
     *
     * @param createtime the value for sys_con_user_role.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.modifytime
     *
     * @return the value of sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.modifytime
     *
     * @param modifytime the value for sys_con_user_role.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_con_user_role.discard
     *
     * @return the value of sys_con_user_role.discard
     *
     * @mbggenerated
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_con_user_role.discard
     *
     * @param discard the value for sys_con_user_role.discard
     *
     * @mbggenerated
     */
    public void setDiscard(String discard) {
        this.discard = discard == null ? null : discard.trim();
    }
}