package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.pername
     *
     * @mbggenerated
     */
    private String pername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perid
     *
     * @mbggenerated
     */
    private String perid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.discard
     *
     * @mbggenerated
     */
    private String discard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.pername
     *
     * @return the value of sys_permission.pername
     *
     * @mbggenerated
     */
    public String getPername() {
        return pername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.pername
     *
     * @param pername the value for sys_permission.pername
     *
     * @mbggenerated
     */
    public void setPername(String pername) {
        this.pername = pername == null ? null : pername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perid
     *
     * @return the value of sys_permission.perid
     *
     * @mbggenerated
     */
    public String getPerid() {
        return perid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perid
     *
     * @param perid the value for sys_permission.perid
     *
     * @mbggenerated
     */
    public void setPerid(String perid) {
        this.perid = perid == null ? null : perid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.description
     *
     * @return the value of sys_permission.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.description
     *
     * @param description the value for sys_permission.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.createtime
     *
     * @return the value of sys_permission.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.createtime
     *
     * @param createtime the value for sys_permission.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.modifytime
     *
     * @return the value of sys_permission.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.modifytime
     *
     * @param modifytime the value for sys_permission.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.discard
     *
     * @return the value of sys_permission.discard
     *
     * @mbggenerated
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.discard
     *
     * @param discard the value for sys_permission.discard
     *
     * @mbggenerated
     */
    public void setDiscard(String discard) {
        this.discard = discard == null ? null : discard.trim();
    }
}