package com.chengjs.cjsssmsweb.pojo;

import java.util.Date;

public class UserConRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.con_rp_id
     *
     * @mbggenerated
     */
    private String conRpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.per_id
     *
     * @mbggenerated
     */
    private String perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_con_role_permission.discard
     *
     * @mbggenerated
     */
    private String discard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.con_rp_id
     *
     * @return the value of user_con_role_permission.con_rp_id
     *
     * @mbggenerated
     */
    public String getConRpId() {
        return conRpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.con_rp_id
     *
     * @param conRpId the value for user_con_role_permission.con_rp_id
     *
     * @mbggenerated
     */
    public void setConRpId(String conRpId) {
        this.conRpId = conRpId == null ? null : conRpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.role_id
     *
     * @return the value of user_con_role_permission.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.role_id
     *
     * @param roleId the value for user_con_role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.per_id
     *
     * @return the value of user_con_role_permission.per_id
     *
     * @mbggenerated
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.per_id
     *
     * @param perId the value for user_con_role_permission.per_id
     *
     * @mbggenerated
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.createtime
     *
     * @return the value of user_con_role_permission.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.createtime
     *
     * @param createtime the value for user_con_role_permission.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.modifytime
     *
     * @return the value of user_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.modifytime
     *
     * @param modifytime the value for user_con_role_permission.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_con_role_permission.discard
     *
     * @return the value of user_con_role_permission.discard
     *
     * @mbggenerated
     */
    public String getDiscard() {
        return discard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_con_role_permission.discard
     *
     * @param discard the value for user_con_role_permission.discard
     *
     * @mbggenerated
     */
    public void setDiscard(String discard) {
        this.discard = discard == null ? null : discard.trim();
    }
}